# -------------------------------------------+
# oh-my-zsh template                         #
# -------------------------------------------+
ZSH=$HOME/.oh-my-zsh

DISABLE_AUTO_UPDATE="true"
ZSH_THEME="simple"
plugins=(gem brew bundler)

source $ZSH/oh-my-zsh.sh

# -------------------------------------------+
#  Customization                             #
# -------------------------------------------+

# completion
autoload -U compinit
compinit

# do not display variable name in a prompt
# if variable's value matches a current path
setopt no_auto_name_dirs

# automatically enter directories without cd
setopt auto_cd

# stop annoying beeping
setopt no_beep

# use vim as an editor
export EDITOR=vim

# aliases
if [ -e "$HOME/.aliases" ]; then
  source "$HOME/.aliases"
fi

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi # rbenv init
# export CC=/usr/bin/gcc-4.2 # CLI tools
export CC=/usr/local/bin/gcc
export CFLAGS="-I/opt/X11/include" # ruby 1.8.7 needs X11 to build
export PATH=/usr/local/bin:/usr/local/sbin:$PATH # look for brew packages first
export PATH=$PATH:~/work/div/scripts
export PATH=$PATH:~/.composer/vendor/bin


# Solarized GNU Colors
if [ -e "$HOME/.zsh/dircolors/dircolors.256dark" -a $+commands[dircolors] ]; then
  # install coreutils to have gdircolors
  eval `gdircolors $HOME/.zsh/dircolors/dircolors.256dark`
fi

# Add bin dir
if [ -e "$HOME/.bin" ]; then
  export PATH=$PATH:$HOME/.bin
fi

# pass <C-s> and other terminal keys to vim
stty -ixon

# ignore duplicate history entries
setopt HIST_IGNORE_ALL_DUPS

# keep TONS of history
export HISTSIZE=4096
export SAVEHIST=10240
export HISTFILE=~/.zsh_history

setopt incappendhistory
setopt share_history
setopt extended_history
setopt histallowclobber
setopt histreduceblanks

# automatically pushd
setopt auto_pushd
export dirstacksize=5

# awesome cd movements from zshkit
setopt AUTOCD
setopt AUTOPUSHD PUSHDMINUS PUSHDSILENT PUSHDTOHOME
setopt cdablevars

# Try to correct command line spelling
setopt CORRECT
unsetopt CORRECT_ALL

# Don't autorename the title
export DISABLE_AUTO_TITLE="true"

# Enable extended globbing
setopt EXTENDED_GLOB

# Jump between projects
export PROJ_HOME=$HOME/work
function f () {if [[ -e $PROJ_HOME/div/$1 ]] then cd $PROJ_HOME/div/$1; else cd $PROJ_HOME/div; fi}
compctl -/ -W $PROJ_HOME/div f

function z () {if [[ -e $PROJ_HOME/projects/$1 ]] then cd $PROJ_HOME/projects/$1; else cd $PROJ_HOME/projects; fi }
compctl -/ -W $PROJ_HOME/projects z

function g () {if [[ -e $PROJ_HOME/gig/$1 ]] then cd $PROJ_HOME/gig/$1; else cd $PROJ_HOME/gig; fi }
compctl -/ -W $PROJ_HOME/gig g

function a () {if [[ -e $PROJ_HOME/aa/$1 ]] then cd $PROJ_HOME/aa/$1; else cd $PROJ_HOME/aa; fi }
compctl -/ -W $PROJ_HOME/aa a

function s () {if [[ -e $PROJ_HOME/stich/$1 ]] then cd $PROJ_HOME/stich/$1; else cd $PROJ_HOME/stich; fi }
compctl -/ -W $PROJ_HOME/stich s

function t () {if [[ -e $PROJ_HOME/teensafe/$1 ]] then cd $PROJ_HOME/teensafe/$1; else cd $PROJ_HOME/teensafe; fi }
compctl -/ -W $PROJ_HOME/teensafe t

# teamocil completion
compctl -g '~/.teamocil/*(:t:r)' teamocil

# makes color constants available
autoload -U colors
colors

# enable colored output from ls, etc
export CLICOLOR=1
export LSCOLORS=ExGxCxDxBxegedabagacad

# expand functions in the prompt
setopt prompt_subst

# nvm
export NVM_DIR=~/.nvm
. $(brew --prefix nvm)/nvm.sh

# tmuxifier
export PATH="$HOME/.tmuxifier/bin:$PATH"
export TMUXIFIER_TMUX_OPTS="-2"
export TMUXIFIER_LAYOUT_PATH=~/.tmuxifier/layouts
eval "$(tmuxifier init -)"
alias disney='tmuxifier load-session disney'
alias aa='tmuxifier load-session aa'
alias magsaya='tmuxifier load-session magsaya'
alias rails6='mtt_cms_api_uri=https://cms-dev6.mh.disney.io/ bundle exec rackup -p 9292'
alias railslocal='mtt_cms_api_uri=http://cms.local.diznee.net:3003 bundle exec rackup -p 9292'


# OPAM configuration
. /Users/div/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true
export PATH="/usr/local/opt/openssl/bin:$PATH"
